### ISSUE TITLE
Remove terralith, document the effects/notable improvements it has on everything. See if the generation is cool enough to stand on its own. If not, try out tectonic, and also take not of how compatible it is.

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#103]
Known things removing terralith does:
- brings back glowstone canyon generation
- fixes glowshroom, galosphere cave generation
- makes gen features like ametrine flowers and structures spawn more often/consistent
Known things tectonic does:(add to this list)

**Comment by GildedToxin** [comment]
Well need to redo the CF page and images - we already have null scape images on there when we dont have it in the pack

**Comment by ISOUL22** [comment]
replaced with tectonic and a quick fly around test with render at 30 and shaders was much better than with terralith still need to test for biome conflicts
glimmering weald still takes over all deepslate caves, must remain disabled

**Comment by ISOUL22** [comment]
terralith is now gone forever, however we still need to deal with incendium since it's preventing glowstone canyons from generating in the nether and causes a lot of lag
