### ISSUE TITLE
Remove paraglider horned statues from spawning

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#110]
i opened a issue in the paraglider issues github but they havent responded, i disabled the structures but they still show up

**Comment by GildedToxin** [comment]
We can just block swap it with air, but tbh the statues are kinda cool so I vote to leave them in with no functionality

**Comment by Jonah-Hansen** [comment]
seems like they arent spawning as of 1.6.1/16.2
