### ISSUE TITLE
Shaders settings fixes an issue with dungeons gear armor following ur crosshair

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#113]
My shader settings meant for performance fix a visual bug where dungeons gear armor model follows your crosshair at like 20 blocks away, I now have to add my model shader settings to yosby so it actually fucking applies cuz it has supposed to have been the default settings shipped with the pack but it wasnt this whole time

**Comment by GildedToxin** [comment]
No more dungeon gear 😔
