### ISSUE TITLE
Fully Test animal respawn mod

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#128]
"This mod seems to not work properly. it despawns baby animals of different color. 
especially pigs. 
The yellow babies, and dark ones despawn 100% as soon as i walk out of range, while the normals ones seem to be persistent."
This mod is supposed to make animals despawn normally unless bred, fed, tamed or named. This might be coincidence, like when renko reported this but it was really just a kitsune attack, but we should still document how well each of these four things work.

**Comment by GildedToxin** [comment]
Removing this mod - closing issue
