### ISSUE TITLE
Pillagers missing in outposts

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#130]
Likely spawn balance utility not applying them to their structureweight txt file correctly, or modded outposts having some datapack conflict. Test in game to see if replicable, if they respawn, etc and what the cause is

**Comment by GildedToxin** [comment]
Just spawned in world next to one, none spawned

Seed for testing: 9036551853099977176

**Comment by GildedToxin** [comment]
![Image](https://github.com/chocolate-edition/Chocolate-Edition/assets/66807613/fcbbc4db-24fa-4852-bf1a-8a2975346873)

Looks like its good now
