### ISSUE TITLE
Remove Glimmering Weald and related

### ISSUE THREAD

**Issue by ISOUL22** [chocolate-edition/Chocolate-Edition#138]

**Comment by guyperson0** [comment]
I've tested this and it doesn't seem to be true; the problem is that the Glimmering Weald is disabled, so the attracting item isn't the Glow Shroom, it's Diamonds.

**Comment by GildedToxin** [comment]
Glimmering Weald was tested and spawned *everywhere* also caused issues with deep dark not spawnning

**Comment by ISOUL22** [comment]
better if we just update relevant recipes and tool tips to not include the glimmering weald at all
- ct script
- qb tooltips

**Comment by GildedToxin** [comment]
Fixed!
