### ISSUE TITLE
Tetra pickaxes doesn't drop amertrine ore when mined

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#15]
Also there was some end blocks that also didnt drop like void shale maybe

**Comment by ISOUL22** [comment]
also not working:
- magmanum ore
- the entire void shale family
- malachite ore
- bismuth ore

**Comment by Jonah-Hansen** [comment]
seems to be all stone types from iter and enlightened. pickarang also does not work on them

**Comment by GildedToxin** [comment]
Of note:

Not all blocks are effected just some, maybe we could look into the inconsistancy for a soultion?

**Comment by Jonah-Hansen** [comment]
> Of note:
> 
> Not all blocks are effected just some, maybe we could look into the inconsistancy for a soultion?

which arent? from my experimenting is was everything classified as `stone`

**Comment by Jonah-Hansen** [comment]
closed by #206

**Comment by Jonah-Hansen** [comment]
so theres a bug in crafttweaker that causes this fix to error out sometimes. supposedly a fix will be in the next minor version 10.1.53

**Comment by Jonah-Hansen** [comment]
will be closed again once #224 is merged. craftweaker 10.1.53 or higher is required.

**Comment by Jonah-Hansen** [comment]
cosed by https://github.com/chocolate-edition/Chocolate-Edition/pull/224/commits/8189479efa10492a3d86a7023a8f4db601bcc86c
on #224
