### ISSUE TITLE
Blue skies mega issue

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#153]
- [ ] [Make mobs from the Renko's list spawn in Blue Skies. List in chocolate-obsidian/important
- [ ] Make UP weapons work w bc
- [ ] Make UP weapons not damage dropoff in bs
- [ ] Add codenames to spawn eggs and entities
- [ ] Make incubator, dna flask, dna fridge, cultivator, insulator all crafted w bs mats
- [ ] possibly try out ore stages to only make UP fossils spawn after expert mode
- [ ] Make bs mobs neutral
- [ ] figure out how to integrate plants
- [ ] shaded citadel
- [ ] white palace
- [ ] dawn ruins 
- [ ] sunken submarines
- [ ]

**Comment by GildedToxin** [comment]
Done with 1.6!
