### ISSUE TITLE
Loot replacements Mega Issue

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#156]
Universal
- [ ] EVERYWHERE replace seeds with food

Group of structures

- [ ] Desert structures have 
- [ ] 

Specific
- [ ] in the casino towers have beer cards and board games
- [ ] in the shiraz palace have gems gold and amber
- [ ] in the village harbor have a metric shitton of tea

**Comment by GildedToxin** [comment]
I’m removing:

Potatos, carrots, melon seeds, beet root seeds, pumpkin seeds, onions, tomato seeds, cabbage seeds, and flax seeds from loot
