### ISSUE TITLE
NPC Mega Issue

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#157]
Give all 64 npcs trades

- [ ] 

Make npcs spawn in structures

- [x] a

Nexus NPC Variants

- [x] Summoner Bankteller
- [x] Alchemist Bankteller
- [ ] Enderling Traveler Fisherman
- [ ] 
CONFIGURE NPCS IN COMMONTOML

Advice

- [ ] Guy:Tomes, the shop items
Burning Ashes
Summoning items
Enchanted golden apples
Astral Dust

**Comment by GildedToxin** [comment]
This is out of date
