### ISSUE TITLE
QBO Tutorial in Welcome

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#158]
i think we should make the tutorial in the quest book just be a few things marked as vital to the pack: quest book inv button in top left, press u and r on an item for recipes or info, search in bottom right, press j to toggle jei, and a to bookmark

**Comment by ISOUL22** [comment]
this can be part of the welcome chapter

**Comment by RichPrune** [comment]
no it cant be part of a chapter it has to be the WHOLE chapter

**Comment by ISOUL22** [comment]
i will do my magic and you will like it, because when you tried no one read it....
