### ISSUE TITLE
Modify Lucky Rock item pool

### ISSUE THREAD

**Issue by guyperson0** [chocolate-edition/Chocolate-Edition#163]
basically add more stuff cause it'd be fun:
- Raw Iron over Iron Ingot
- Raw Gold over Gold Ingot
- Raw Silver
- Ametrine Shard
- Voidquartz Shard
- Raw Copper
- Raw Zinc
- Amethyst Shard
- Ruby
- Jade
- Aquamarine
- Onyx
- Nether Quartz
- Ancient Geode
- Piece of Dark Metal
- Stone Geode

**Comment by Jonah-Hansen** [comment]
closed by https://github.com/chocolate-edition/Chocolate-Edition/commit/5bd5f8d4ec32f87033a75fa8858ce4c1446d49c3
