### ISSUE TITLE
Stage Granting is done in FTB Quests

### ISSUE THREAD

**Issue by guyperson0** [chocolate-edition/Chocolate-Edition#165]
Just for consistency's sake, and ideally this grants the stage to all players on the same team at once

Also, need to test the following scenario:
- Say Person A and Person B are on the same team, thus FTB Quest's team reward grants them both the same reward for completing the same quest
- A completes an Eye while B is offline, thus granting them the relevant stage as a quest reward
- When B logs on, will they also get the quest reward immediately upon log-in through auto-claim? Or does the reward only trigger in the immediate moment the quest is completed, or some other scenario in which B may not be able to get their reward?

**Comment by GildedToxin** [comment]
closed by #216
