### ISSUE TITLE
Extra or unnecessary config folders and files included in release

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#18]
there's config folders/files for mods that are no longer in the pack and some have data that shouldn't be there(JEI has all the data from christi's test worlds)

**Comment by ISOUL22** [comment]
turns out i can't fix this is git, christi will have to do it when she makes the .zip to upload to curse

**Comment by ISOUL22** [comment]
double check for other files that shouldn't be in the .zip, such as:
- backups of test worlds
- map data
- logs
and anything else that isn't mission critical
