### ISSUE TITLE
Decrease Spawn Rate of Blastling and Watchling in the End dimension

### ISSUE THREAD

**Issue by RUsami** [chocolate-edition/Chocolate-Edition#217]
Decrease Spawn Rate of Blastling and Watchling in the End dimension
I looked too I think there is too many too, you cannot go anywhere without fighting a gigaton of them

**Comment by RUsami** [comment]
the last one of them are the Snarelings

**Comment by Jonah-Hansen** [comment]
dungeones mobs has no config for spawn rates :( also the end endermen from endermen overhaul feels really high. just end dimension spawn rates are really high all together. not sure how to fix though especially since SBU is gone :/

**Comment by Jonah-Hansen** [comment]
closed by #272
