### ISSUE TITLE
Replace diamond armor recipe so it includes iron armor and keep enchants

### ISSUE THREAD

**Issue by Huskykyle** [chocolate-edition/Chocolate-Edition#248]

**Comment by GildedToxin** [comment]
we could always smith iron chest plate with diamond and it spits out diamond with enchants

**Comment by Huskykyle** [comment]
should we do diamond block to upgrade it on the smithing table? alternatively, can the smithing table use multiple of the same item, so that it would be iron boots + 4 diamonds instead of 9 diamonds for a block?

**Comment by Huskykyle** [comment]
i just made it as a diamond block, we can justify the use of extra diamonds as the fact that you can keep the enchantments.

**Comment by Huskykyle** [comment]
closed by #247
