### ISSUE TITLE
Remove villager trading that gives easy emeralds, add and keep useful villager trades

### ISSUE THREAD

**Issue by Huskykyle** [chocolate-edition/Chocolate-Edition#249]

**Comment by Huskykyle** [comment]
Prevents villager trading halls to be the meta. For adding villager trades, librarians will trade some of the ancient tomes from quark. Armorsmith selling artifacts. Farmers sell farmers' delight foods.  Librarians wont sell pet enchants so that they sell more useful things. Maybe make tamer sell them instead?

**Comment by GildedToxin** [comment]
Im gonna quickly add onto this, actually make mending unable to be traded for since it seems what chrisit used didnt work

**Comment by Jonah-Hansen** [comment]
close by #389
