### ISSUE TITLE
Make Born in Chaos Towers spawn less often in snowy/flat biomes

### ISSUE THREAD

**Issue by RUsami** [chocolate-edition/Chocolate-Edition#278]
too much

**Comment by GildedToxin** [comment]
I also don't think we can change this

**Comment by RUsami** [comment]
![2024-01-21_17 15 56](https://github.com/chocolate-edition/Chocolate-Edition/assets/78971193/6421d61a-dd4a-43a5-9dd5-43e66e1efe22)
