### ISSUE TITLE
Text Appearing in chat when opening a chest/barrel or guide book in Bakery Stove

### ISSUE THREAD

**Issue by RUsami** [chocolate-edition/Chocolate-Edition#280]
![2024-01-21_16 16 33](https://github.com/chocolate-edition/Chocolate-Edition/assets/78971193/c7ee81e6-2e43-4ada-bd78-155a2bef76e3)
![2024-01-21_16 20 31](https://github.com/chocolate-edition/Chocolate-Edition/assets/78971193/1f7b1af6-8b87-439a-b86e-a6cf57e6c842)

**Comment by GildedToxin** [comment]
It's all GUId

**Comment by Jonah-Hansen** [comment]
caused by worldedit mod. safe to remove prior to release
