### ISSUE TITLE
Farm Animals Spawns

### ISSUE THREAD

**Issue by RUsami** [chocolate-edition/Chocolate-Edition#283]
Make farm animals spawn much less often and replace their spawn with wild and rarer animals
Since we don't have animalrespawn anymore. This would make people use more the mob lasso to catch their first farm animals and make more wild animals spawn

**Comment by GildedToxin** [comment]
We dont have mob lasso anymore

**Comment by GildedToxin** [comment]
Animals respawn is back, and we also cant spawn animals with it
