### ISSUE TITLE
Quest Book first open on wrong page

### ISSUE THREAD

**Issue by RUsami** [chocolate-edition/Chocolate-Edition#285]
The QuestBook open the first time on "(Some Outdated)Optional Checklists"
Should it not be on "Welcome !" ?

**Comment by GildedToxin** [comment]
It opens on whatever the first page is, so it should be opening on welcome, have you tried launching a new world?

**Comment by RUsami** [comment]
yes, it's on a fresh world start

**Comment by GildedToxin** [comment]
pain
ill test

**Comment by RUsami** [comment]
maybe I have some config not up top date ??

**Comment by GildedToxin** [comment]
I just tested and it worked on my end

**Comment by GildedToxin** [comment]
![image](https://github.com/chocolate-edition/Chocolate-Edition/assets/66807613/9bdee5ce-12ea-4655-ae5f-a37ecfe541a2)

**Comment by RUsami** [comment]
oo might be my config ???

**Comment by GildedToxin** [comment]
Maybe? Can a 3rd person test and see?
