### ISSUE TITLE
Repair option for artifiacts

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#32]

**Comment by guyperson0** [comment]
Apparently I'm doing this for Dungeons Gear too yippee

**Comment by Jonah-Hansen** [comment]
dubious dust crafting and repair tested. 

closed by https://github.com/chocolate-edition/Chocolate-Edition/commit/026d158d385dc0dd86f6d25fc7434e3c386ad8de#diff-c6e658c90cc015209a3f94e611fb377ef19727405bbe1048cc071afd9be63651
