### ISSUE TITLE
ungate tetra scrolls

### ISSUE THREAD

**Issue by Jonah-Hansen** [chocolate-edition/Chocolate-Edition#338]

**Comment by Jonah-Hansen** [comment]
most of the tetra scrolls would be nice to have at stage 1 or 2

**Comment by Jonah-Hansen** [comment]
All the base Tetra schematics are plenty balanced for Stage 1 
The craftable ones should be stage 2.
The Flamberge has crazy cleave range and bonus stats 
The Katana isn't too powerful but its a very fast 2 handed weapon
The Crucible and Murasama have expensive recipes that require Stage 2 items anyways, so they can't be gotten Stage 1
Same with the Rending Scissors

**Comment by iakfar** [comment]
think basically all of them could be ungated. the good ones, rending scissors and murasama, require netherite anyways.

**Comment by Jonah-Hansen** [comment]
closed by #437
