### ISSUE TITLE
Disable etheral wings 

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#343]
ulimited creative flight, no dura, removes fall damage, beleive to be gotten from loot table, breaks spectator fly speed
https://discord.com/channels/945364406609514517/1208452426575642654/1208452426575642654

**Comment by GildedToxin** [comment]
Its a reward for a quest (I think its for the undead eye)

**Comment by Jonah-Hansen** [comment]
cant find the wings in the qb anywhere so someone must have removed at some point!

**Comment by iakfar** [comment]
can confirm its gone, heres where it was
![image](https://github.com/user-attachments/assets/91ec92b2-5fae-4bb5-8c38-8012741d5936)
