### ISSUE TITLE
Add some needed item descriptions for next update

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#36]
- [x] All gated items should have a description stating that they're gated ig
- [ ] All materials used to make gated items should have a description saying so
- [ ] Chemical X and similar items need descriptions
- [x] Cataclysm summoning items
- [ ] Holosphere
- [x] Enchantment Table (Matrix Enchanting)
- [ ] Eye Ingredient items
- [x] Backpack (too many slow you down)
- [x] Mending cannot be gotten from Villagers
- [x] Astral Dust brewing capabilities
- [x] Infusion Table
- [ ] Quest Book should state Quests can be accessed via inventory button or keybind
- [x] Dubious Dust and Artifacts mention Artifact repair mechanics
- [ ] Electric Paddle specify function
- [ ] Specify stats boosted from Cracked Crown

**Comment by Jonah-Hansen** [comment]
doesnt seem to actually show up properly in game

**Comment by GildedToxin** [comment]
I'll check these, they should be in jei
