### ISSUE TITLE
anthill not spawning ants?

### ISSUE THREAD

**Issue by Jonah-Hansen** [chocolate-edition/Chocolate-Edition#361]
havent tested outsdide the dev server yet but ant hills seem to generate empty. needed to use a pupa to create a new ant hill in order to find gongylidia

**Comment by GildedToxin** [comment]
Is there a chance that they got animal respawned?

**Comment by Jonah-Hansen** [comment]
ooh that could be it

**Comment by GildedToxin** [comment]
Any updates on this? No one has been reporting anything

**Comment by Jonah-Hansen** [comment]
I dont think its happening anymore. idk the 1.5.5 server was bugged or something
