### ISSUE TITLE
Add yeti hide -> 2 leather crafting table recipe

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#37]

**Comment by guyperson0** [comment]
Might be nitpicky but I think maybe using farmer's delight cutting board for this would make more sense? (also to give that thing more uses)

**Comment by GildedToxin** [comment]
I actually like that a lot, I'll see what I can do

**Comment by guyperson0** [comment]
Should be something like
<recipetype:farmersdelight:cutting>.addRecipe("yeti_hide_to_leather", <item:cnb:yeti_hide>, [(<item:minecraft:leather> * 2)], <tag:items:forge:tools/knives>, );
