### ISSUE TITLE
can we remove the parcool book pls

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#378]
half the info is incorrect u cant do cat jumps and shit

**Comment by GildedToxin** [comment]
I know you mentioned in the past not wanting the player to start with the parcool book 
You could have an invisible quest in the book that triggers on picking up the parcool book, that has no toast and collects the item

**Comment by GildedToxin** [comment]
My idea wont work, only thing I can think of is a /clear inv at the start of the game but I worry that will screw with people, gonna give it a shot and yall can give thoughts

**Comment by iakfar** [comment]
its supposedly given with an advancement. might be able to datapack remove the advancement

**Comment by GildedToxin** [comment]
The clear works for now, we can always switch it to DP later or if yall think its too risky

I put it in its own section so it doesnt get reset (and your inv cleared) on using the debug reset quests thing

**Comment by GildedToxin** [comment]
I didnt work 😌

**Comment by Jonah-Hansen** [comment]
closed by #493
