### ISSUE TITLE
prisnautilus items are seemingly unobtainable

### ISSUE THREAD

**Issue by Jonah-Hansen** [chocolate-edition/Chocolate-Edition#398]
https://discord.com/channels/945364406609514517/1139304955262537890/1244386091251929250

weathering tome and wave of abyss are apparently not craftable and don't seem to actually drop from the prisnautilus

**Comment by GildedToxin** [comment]
None of the weapons from the bosses drop, you get them from the gift boxes they do randomly (they are low odds ngl) but you get them none the less!
