### ISSUE TITLE
The Acknowledgement, book from enigmatic legacy seems to not be craftable(original recipe is a book+lantern) this book is supposed to explain artifacts from EL

### ISSUE THREAD

**Issue by ISOUL22** [chocolate-edition/Chocolate-Edition#43]

**Comment by guyperson0** [comment]
It's disabled in the config becauase christi just kind of did that to everything in EL, but it might be for the better since half the book's information is inaccurate to the modpack in its current state (items such as Heart of Earth are disabled, Seven Curses is completely removed rn, etc.)
