### ISSUE TITLE
Fix sugar giving hunger 4

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#450]
Shouldn't give any debuff

**Comment by iakfar** [comment]
this should be fixed by zipping the chocoflavours datapack correctly. still not sure what else is in there. see bee queen stuff/removing a bugged wither storm advancement and idr what else

**Comment by iakfar** [comment]
has a few other things in that zip that im not sure are still wanted. such as the beacon block changes and the bosses despawning at morning.
don't really think we want bosses despawning at morning unless they're gonna start randomly spawning again.
not sure if the beacon blocks thing is replacing the beacon blocks or adding more options, if its the first it will cause enlightend incident 2

![Image](https://github.com/user-attachments/assets/76df4cd1-b576-4aff-9279-c4c200057f3a)

**Comment by GildedToxin** [comment]
![Image](https://github.com/user-attachments/assets/0de692a3-6a3c-41a7-88ba-15d71ae13a9b)

**Comment by GildedToxin** [comment]
Closed by #607
