### ISSUE TITLE
investigate mummy crashing

### ISSUE THREAD

**Issue by Jonah-Hansen** [chocolate-edition/Chocolate-Edition#508]
rotten creatures mummy (in the serpent labyrinth) causes crashing for players nearby

**Comment by Perchin577** [comment]
I have this same problem, and I can no longer enter the multiplayer server

**Comment by Jonah-Hansen** [comment]
@Perchin577 im aware :) do you recall which dungeon it was?

**Comment by Perchin577** [comment]
Yes, it was a temple with 2 snake statues on each side.

**Comment by Perchin577** [comment]
![image](https://github.com/user-attachments/assets/f7617069-7108-49bd-8e7e-86b1ffe5844c)

https://www.curseforge.com/minecraft/mc-mods/idas

**Comment by Jonah-Hansen** [comment]
closed by #511

**Comment by Perchin577** [comment]
https://mclo.gs/cMRBrLo
Hello, if you see this could you help me, I have this problem in the same dungeon.

**Comment by Jonah-Hansen** [comment]
@Perchin577 we disabled the mummies from spawning but any existing ones from before the update may still cause crashing. you will want to do `/kill @e[type=rottencreature:mummy]` near the serpent labyrinth dungeon to remove them

**Comment by Perchin577** [comment]
I'm sorry to talk to you here, I just don't know where I can report these bugs and I saw this page, I'm on the chocolate multiplayer server and that happened. The first time I managed to get out of the dungeon after they were removed. but now it happened again. I try to enter the server and the game closes, I will see if I can enter, thanks.

**Comment by Jonah-Hansen** [comment]
@Perchin577 please open a support ticket let with the official server host https://discord.com/invite/playcdu
