### ISSUE TITLE
Add auto 3rd person mod

### ISSUE THREAD

**Issue by Jonah-Hansen** [chocolate-edition/Chocolate-Edition#527]
With shoulder surfing, it might be nice to try out a mod that auto swaps to 3rd person when riding a horse or boat or extra for example.

**Comment by GildedToxin** [comment]
https://discord.com/channels/945364406609514517/1271965486976077845/1275121161348583566 The people dont want it sadly

**Comment by Jonah-Hansen** [comment]
should we still add it but leave it disabled by default? I personally really like it at least for boats, and for horses its nice too

**Comment by GildedToxin** [comment]
I'm down - the vote was pretty split so we could honestly just enable it for those 2

**Comment by Jonah-Hansen** [comment]
maybe we just wait until we put together a proper "wiki"/ important keyinds/info/tips and tricks page and in there we can mention how to turn it off. then I think it would be reasonable to have it on by default without getting too many questions about how to disable it!

**Comment by GildedToxin** [comment]
I like it! and worst comes to worst they can just hit f5 and change it

**Comment by GildedToxin** [comment]
closed by #571
