### ISSUE TITLE
Autobrewing with Create mixers makes wrong potions

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#545]
[Autobrewing with Create mixers makes wrong potions](https://discord.com/channels/945364406609514517/1275062545782280276)

**Comment by GildedToxin** [comment]
So it seems like when doing autoamated brewing, if I add 2 redstone it counts as a recipe and then brews an uncraftable poition, which then brews into knockback resistance

![Image](https://github.com/user-attachments/assets/89038263-0380-47a7-9b19-0ea634c55bf1)

Fixing this would require adding a recipe for every potion that has an extended time with redstone, and even then I assume itll trigger for 3 or 4

Unless anyone has ideas imma close this for now

**Comment by iakfar** [comment]
is this a bug with the mod...? so weird
