### ISSUE TITLE
remove default controller pairing

### ISSUE THREAD

**Issue by Jonah-Hansen** [chocolate-edition/Chocolate-Edition#555]
in 1.8.0 a controller pairing was left on, so is a player has an xinput controller connected, it will be automatically paired and may give unintended inputs. 

by default, no controllers should be paired so that the user can pair the correct one themselves if they wish to use controllable

see https://github.com/chocolate-edition/Chocolate-Edition/pull/547#discussion_r1730612213

**Comment by GildedToxin** [comment]
closed by #568
