### ISSUE TITLE
prot not in candles

### ISSUE THREAD

**Issue by iakfar** [chocolate-edition/Chocolate-Edition#559]
copying the entire line from the dev branch 
		"Influences List" = ["minecraft:unbreaking", "minecraft:fire_protection,enigmaticlegacy:torrent,alexsmobs:lavawax,enlightened_end:frost_aspect", "minecraft:knockback,minecraft:punch,unusualend:boloks_fury,farmersdelight:backstabbing,enigmaticlegacy:sharpshooter,alexsmobs:straddle_jump", "minecraft:feather_falling", "minecraft:looting,minecraft:fortune,minecraft:luck_of_the_sea", "minecraft:blast_protection", "minecraft:silk_touch,minecraft:channeling", "minecraft:bane_of_arthropods", "minecraft:,alexsmobs:serpentfriend", "minecraft:respiration,minecraft:loyalty,minecraft:infinity,alexsmobs:board_return,enigmaticlegacy:ceaseless", "minecraft:sweeping,minecraft:multishot", "minecraft:efficiency,minecraft:sharpness,minecraft:lure,minecraft:power,minecraft:impaling,minecraft:quick_charge", "minecraft:aqua_affinity,minecraft:depth_strider,minecraft:riptide,unusualfishmod:unusual_catch", "minecraft:thorns,minecraft:piercing", "minecraft:fire_aspect,minecraft:flame", "minecraft:smite,minecraft:projectile_protection"]

**Comment by GildedToxin** [comment]
Adding onto this, frost aspect doesnt actually work

**Comment by GildedToxin** [comment]
closed by #568
