### ISSUE TITLE
Create's crushed silver ore missing smelting recipe

### ISSUE THREAD

**Issue by tlannigan** [chocolate-edition/Chocolate-Edition#60]

**Comment by Jonah-Hansen** [comment]
wasnt actually fixed?

**Comment by GildedToxin** [comment]
It was fixed, we added new silver this update though so that might be it

**Comment by GildedToxin** [comment]
![Image](https://github.com/chocolate-edition/Chocolate-Edition/assets/66807613/72185a77-d1f1-43b9-8690-0ca92c749538)
![Image](https://github.com/chocolate-edition/Chocolate-Edition/assets/66807613/62a2bafc-b7cc-48b3-8e8d-fa0b54dec2b1)

**Comment by Jonah-Hansen** [comment]
oh nvm then!
