### ISSUE TITLE
Celestial Cores are unobtainable.

### ISSUE THREAD

**Issue by Luviam** [chocolate-edition/Chocolate-Edition#602]
Celestial Cores from Celestisynth are currently unobtainable as they lack any recipe.

**Comment by iakfar** [comment]
is it not post wither storm in the shop?
![image](https://github.com/user-attachments/assets/a89a9889-8b3c-4537-a639-f84818319ac0)

**Comment by Luviam** [comment]
Oh, didn't think of checking the quest book's code for it being obtainable there. Guess I need to kill the witherstorm for it to even show up. Thanks, I probably will just stop playing the modpack as I am not going through that effort to get a celestial core lmao.
