### ISSUE TITLE
Add Irons Spellbooks (kill me)

### ISSUE THREAD

**Issue by guyperson0** [chocolate-edition/Chocolate-Edition#61]
i just want to feel something again

- [x] Recipes for regular stuff
- [ ] Balancing all the spells (pain)
- [ ] Recipes for the Ender Spells, make them all endgame I guess

**Comment by GildedToxin** [comment]
We arent doing this anymore - as it crashes the nexus lol
(and would just be hell to balance)
Closing the issue
