### ISSUE TITLE
move the end ships from WDA down

### ISSUE THREAD

**Issue by iakfar** [chocolate-edition/Chocolate-Edition#612]
its already done i just need to make a pull request+branch but im eepy

maybe test it too, dude in discord said it works tho

**Comment by iakfar** [comment]
older patches have it at 160 before they moved it up, latest 19.2 patch changed it to 250. all the patchnotes for versions above it don't mention it but at some point they changed it to 200. gonna change it to 200 and see if it generates fine

**Comment by GildedToxin** [comment]
Closed by #615
