### ISSUE TITLE
Rename Mega issue

### ISSUE THREAD

**Issue by guyperson0** [chocolate-edition/Chocolate-Edition#72]
**LEAVE SUGGESTIONS**
- [x]  Blue Skies cherry stuff 
- [x]  Rope from supplementaries / farmers delight -> Hanging Rope / Rope 
- [x]  Insatiable Pearl / Blue Skies Pearl / Otter Pearl -> Tempest Pearl / Frozen Pearl / Pearl 
- [x]  Evil Eye -> Clockwork Eye 
- [x]  Rename quark's backpack to inventory upgrade
- [x] Rename iters ice bricks to smooth ice bricks
- [x] Platypus to duck billed platypus
- [x] Blue skies maple
- [x] ender golem to obsidian golem
- [x] Obscureapis Astral dust to Crystal Dust

**Comment by GildedToxin** [comment]
I changed your list to a check list for better read ability

**Comment by GildedToxin** [comment]
I cant rename every compat items, other wise done



![Image](https://github.com/user-attachments/assets/2a51fa96-0de4-461d-a6e3-bd5e61686635)

**Comment by Jonah-Hansen** [comment]
closed by #480
