### ISSUE TITLE
Add more enchantments to Matrix Enchanting candle influencing

### ISSUE THREAD

**Issue by guyperson0** [chocolate-edition/Chocolate-Edition#75]
https://docs.google.com/spreadsheets/d/1OZP8Ts6COUlxJoPR72ogOVFEwq2g0z4BDkgqkBLVwck

**Comment by GildedToxin** [comment]
There is a text file with all non-mc and non-dungeon gear in the discord

**Comment by guyperson0** [comment]
Need them grouped by colour...
