### ISSUE TITLE
Make player spawn with questbook

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#76]

**Comment by GildedToxin** [comment]
doesnt hurt to have them spawn with it nice QOL

**Comment by guyperson0** [comment]
ok done

**Comment by guyperson0** [comment]
why

**Comment by RichPrune** [comment]
but then players r gonna think they have to use the book, and id rather they use the inv button

**Comment by ISOUL22** [comment]
people have come into the discord asking how to open the qb lol, just i'll mention the inventory button in the welcome section

**Comment by RichPrune** [comment]
fine
