### ISSUE TITLE
Damaged Tools and Armor can be used before their stage locks

### ISSUE THREAD

**Issue by GildedToxin** [chocolate-edition/Chocolate-Edition#8]

**Comment by GildedToxin** [comment]
ALL items with dura can - fixing this soon TM

**Comment by RichPrune** [comment]
u were gonna add .anyDamage to all the createstages restricted items right?

**Comment by Jonah-Hansen** [comment]
closed by https://github.com/chocolate-edition/Chocolate-Edition/commit/64252b98323ec8d9ff8753a20e8c1cab88bbf7a0
