### ISSUE TITLE
Mod Changes

### ISSUE THREAD

**Issue by ISOUL22** [chocolate-edition/Chocolate-Edition#82]
- [x] Update JEITweaker to latest edition
- [x] Update Enigmatic Legacy to latest edition so it stops sending the message lol
- [x] Add RecipeStages
- [x] FTB xMod Compat
- [x] Journeymap over FTB Maps
- [x] No mo' Effishiency

**Comment by ISOUL22** [comment]
done, and uploaded to drive

**Comment by GildedToxin** [comment]
perfect! ill do the scripts now

**Comment by guyperson0** [comment]
I believe we're adding Galosphere and Tectonic as well, and removing Terralith

**Comment by ISOUL22** [comment]
### Updated
- better compatibility checker
- bo's easy npc
- collective
- create
- create: central kitchen
- curios api
- diet
- double doors
- embeddium
- enchantment descriptions
- enlightend
- every compat
- friends & foes
- jeitweaker
- just enough resources
- kubejs
- modernfix
- moodlight library
- naturalist
- necronomicon
- nether depths upgrade
- polymorph
- quark
- supplementaries
- the graveyard
- weaker spiderwebs
### Removed
- straw golem
- terralith
- silentlib
### Added
- journeymap
- journeymap intergration
- journeymap-teams
- ftb xmod compat
- recipe stages
- create confectionery
- k-golems
- satako
- tectonic
- galosphere

**Comment by ISOUL22** [comment]
# DO NOT UPDATE
- Born In Chaos
this list will probably grow :c
