### ISSUE TITLE
Make it so crft F doesn't show temp quests lol

### ISSUE THREAD

**Issue by ISOUL22** [chocolate-edition/Chocolate-Edition#83]
Move Mutant Creeper / Enderman quests from debug/temps chapter to literally anywhere else before release

FTB xMod Compat would allow for people to access the debug menu which has a funny little checkbox quest that removes literally all of their progress and I feel like some bozo is gonna do it and complain to us. So let's just make sure that doesn't happen. Thanks!

**Comment by guyperson0** [comment]
Update on this: There's literally an option for every quest that says "hide in JEI" lmao we're good
