### ISSUE TITLE
Rework villages to be more exclusive

### ISSUE THREAD

**Issue by RichPrune** [chocolate-edition/Chocolate-Edition#99]
I want villages to have more exclusive to them features THAT ARENT ESSENTIAL LIKE MENDING OR ANYTHING STUPID i mean like bounty boards or that wares mod or what im gonna implement w npcs which is have special ones for each village type

**Comment by GildedToxin** [comment]
https://www.curseforge.com/minecraft/mc-mods/bountiful this? but its only for 1.19.4

**Comment by GildedToxin** [comment]
Closing this cuz its just npcs
